# Generated by Django 4.1.7 on 2023-03-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(blank=True, upload_to='images')),
                ('number', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Detailed_desc',
            fields=[
                ('dest_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=20000)),
                ('rating', models.IntegerField(default=5)),
                ('dest_name', models.CharField(max_length=25)),
                ('img1', models.ImageField(blank=True, upload_to='images')),
                ('img2', models.ImageField(blank=True, upload_to='images')),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Adventures',
            },
        ),
    ]
