# Generated by Django 4.1.7 on 2023-03-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_detailed_desc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='detailed_desc',
            options={'verbose_name_plural': 'Adventures'},
        ),
        migrations.AlterField(
            model_name='destination',
            name='img1',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='img2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='img1',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='img2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
